package frontend.reportes;

import backend.principal.FuncionamientoAplicacion;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author michael
 */
public class PrestamosPorCarrera extends javax.swing.JPanel {

    /**
     * Creates new form PrestamosPorCarrera
     */
    public PrestamosPorCarrera() {
        initComponents();
        actualizarTablaPrestamosPorCarrera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
public void actualizarTablaPrestamosPorCarrera() {
        String[] columnaPrestamosPorCarrera = {"Código carrera", "Nombre de carrera", "Carné", "Nombre de estudiante"};
        DefaultTableModel modelo = new DefaultTableModel(columnaPrestamosPorCarrera, FuncionamientoAplicacion.listaPrestamos.size());
        tablaReportes.setModel(modelo);

        TableModel modeloDatos = tablaReportes.getModel();
        /*  for (int i = 0; i < FuncionamientoAplicacion.listaPrestamos.size(); i++) {
            Prestamo estudiante = FuncionamientoAplicacion.listaPrestamos.get(i);
            modeloDatos.setValueAt(estudiante.getCarnet(), i, 0);
            modeloDatos.setValueAt(estudiante.getNombre(), i, 1);
            modeloDatos.setValueAt(estudiante.getCodigoCarrera(), i, 2);
            modeloDatos.setValueAt(estudiante.getFechaNacimiento(), i, 3);*/
    }
}
