package frontend.reportes;

import backend.principal.FuncionamientoAplicacion;
import backend.principal.Prestamo;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author michael
 */
public class PrestamosConMora extends javax.swing.JPanel {

    /**
     * Creates new form PrestamosConMora
     */
    public PrestamosConMora() {
        initComponents();
        actualizarTablaEntregasConMora();
        ajustarColumnaTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaReportes = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables

    public void actualizarTablaEntregasConMora() {
        String[] columnaDevolucionMora = {"No.", "Carnet", "Nombre", "Código de libro", "Título", "Fecha de préstamo", "Fecha de devolución", "Días de atraso", "Mora"};
        DefaultTableModel modelo = new DefaultTableModel(columnaDevolucionMora, FuncionamientoAplicacion.listaPrestamos.size());
        tablaReportes.setModel(modelo);

        TableModel modeloDatos = tablaReportes.getModel();
        for (int i = 0; i < FuncionamientoAplicacion.listaPrestamos.size(); i++) {
            if (FuncionamientoAplicacion.listaPrestamos.get(i).getDiasConMora() != 0) {
                Prestamo prestamo = FuncionamientoAplicacion.listaPrestamos.get(i);
                modeloDatos.setValueAt(String.valueOf((i + 1)), i, 0);
                modeloDatos.setValueAt(prestamo.getEstudiante().getCarnet(), i, 1);
                modeloDatos.setValueAt(prestamo.getEstudiante().getNombre(), i, 2);
                modeloDatos.setValueAt(prestamo.getLibro().getCodigo(), i, 3);
                modeloDatos.setValueAt(prestamo.getLibro().getTitulo(), i, 4);
                modeloDatos.setValueAt(prestamo.getFechaPrestamo(), i, 5);
                modeloDatos.setValueAt(prestamo.getFechaPrestamo(), i, 6);
                modeloDatos.setValueAt(prestamo.getDiasConMora(), i, 7);
                modeloDatos.setValueAt("Q. " + String.valueOf(prestamo.getDiasConMora() * 10), i, 8);
            }
        }
        FuncionamientoAplicacion.guardarSerializableLibros();
    }

    private void ajustarColumnaTexto() {
        TableColumnModel columnModel = tablaReportes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40); // Establecer ancho mínimo inicial a 0
        columnModel.getColumn(0).setMaxWidth(40); // Establecer ancho máximo a 0
        columnModel.getColumn(0).setMinWidth(40); // Establecer ancho mínimo a 0

        int rowCount = tablaReportes.getRowCount();
        int column = 0; // Columna que deseas ajustar

        for (int row = 0; row < rowCount; row++) {
            int width = (int) tablaReportes.getCellRenderer(row, column).getTableCellRendererComponent(tablaReportes, tablaReportes.getValueAt(row, column), false, false, row, column).getPreferredSize().getWidth();
            width += 2 * tablaReportes.getIntercellSpacing().getWidth();
            columnModel.getColumn(column).setPreferredWidth(Math.max(columnModel.getColumn(column).getPreferredWidth(), width));
        }
    }
}
