package frontend.reportes;

import backend.principal.FuncionamientoAplicacion;
import backend.principal.Prestamo;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author michael
 */
public class RecaudadoEnIntervaloTiempo extends javax.swing.JPanel {

    private JTextField textFieldBusqueda;
    private TableRowSorter<TableModel> rowSorter;

    /**
     * Creates new form RecaudadoEnIntervaloTiempo
     */
    public RecaudadoEnIntervaloTiempo() {
        initComponents();
        actualizarTablaIngresosIntervaloTiempo();
        ajustarColumnaTexto();
        agregarCampoBusqueda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables

    public void actualizarTablaIngresosIntervaloTiempo() {
        String[] columnaDevolucionHoy = {"No.", "Carnet", "Nombre", "Código de libro", "Título", "Fecha de préstamo", "Fecha de devolución"};
        DefaultTableModel modelo = new DefaultTableModel(columnaDevolucionHoy, FuncionamientoAplicacion.listaPrestamos.size());
        tablaReportes.setModel(modelo);

        TableModel modeloDatos = tablaReportes.getModel();
        for (int i = 0; i < FuncionamientoAplicacion.listaPrestamos.size(); i++) {
            Prestamo estudiante = FuncionamientoAplicacion.listaPrestamos.get(i);
            modeloDatos.setValueAt(String.valueOf(i + 1), i, 0);
            modeloDatos.setValueAt(estudiante.getEstudiante().getCarnet(), i, 1);
            modeloDatos.setValueAt(estudiante.getEstudiante().getNombre(), i, 2);
            modeloDatos.setValueAt(estudiante.getLibro().getCodigo(), i, 3);
            modeloDatos.setValueAt(estudiante.getLibro().getTitulo(), i, 4);
            modeloDatos.setValueAt(estudiante.getFechaPrestamo(), i, 5);
            modeloDatos.setValueAt(estudiante.getFechaPrestamo(), i, 6);
        }
        FuncionamientoAplicacion.guardarSerializableLibros();
    }

    private void ajustarColumnaTexto() {
        TableColumnModel columnModel = tablaReportes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(0).setMaxWidth(40);
        columnModel.getColumn(0).setMinWidth(40);

        int rowCount = tablaReportes.getRowCount();
        int column = 0;

        for (int row = 0; row < rowCount; row++) {
            int width = (int) tablaReportes.getCellRenderer(row, column).getTableCellRendererComponent(tablaReportes, tablaReportes.getValueAt(row, column), false, false, row, column).getPreferredSize().getWidth();
            width += 2 * tablaReportes.getIntercellSpacing().getWidth();
            columnModel.getColumn(column).setPreferredWidth(Math.max(columnModel.getColumn(column).getPreferredWidth(), width));
        }
    }

    private void agregarCampoBusqueda() {
        textFieldBusqueda = new JTextField();
        textFieldBusqueda.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }
        });
        add(textFieldBusqueda, java.awt.BorderLayout.NORTH);
    }

    private void filtrarTabla(String texto) {
        if (rowSorter == null) {
            rowSorter = new TableRowSorter<>(tablaReportes.getModel());
            tablaReportes.setRowSorter(rowSorter);
        }
        if (texto.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }
}
