package frontend.registrosinformacionnueva;

import backend.principal.Estudiante;
import backend.principal.FuncionamientoAplicacion;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author michael
 */
public class ListadoEstudiantes extends javax.swing.JPanel {

    private JTextField textFieldBusqueda;
    private TableRowSorter<TableModel> rowSorter;

    /**
     * Creates new form ListadoEstudiantes
     */
    public ListadoEstudiantes() {
        initComponents();
        actualizarTablaEstudiantes();
        agregarCampoBusqueda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaEstudiantes = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEstudiantes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables

    private void agregarCampoBusqueda() {
        textFieldBusqueda = new JTextField();
        textFieldBusqueda.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }
        });
        add(textFieldBusqueda, java.awt.BorderLayout.NORTH);
    }

    private void filtrarTabla(String texto) {
        if (rowSorter == null) {
            rowSorter = new TableRowSorter<>(tablaEstudiantes.getModel());
            tablaEstudiantes.setRowSorter(rowSorter);
        }
        if (texto.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }

    public void actualizarTablaEstudiantes() {
        String[] columnas = {"Carné", "Nombre", "Carrera", "Fecha de nacimiento"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, FuncionamientoAplicacion.listaEstudiantes.size());
        tablaEstudiantes.setModel(modelo);

        TableModel modeloDatos = tablaEstudiantes.getModel();
        for (int i = 0; i < FuncionamientoAplicacion.listaEstudiantes.size(); i++) {
            Estudiante estudiante = FuncionamientoAplicacion.listaEstudiantes.get(i);
            modeloDatos.setValueAt(estudiante.getCarnet(), i, 0);
            modeloDatos.setValueAt(estudiante.getNombre(), i, 1);
            modeloDatos.setValueAt(estudiante.getCodigoCarrera(), i, 2);
            modeloDatos.setValueAt(estudiante.getFechaNacimiento(), i, 3);
        }
        FuncionamientoAplicacion.guardarSerializableLibros();
    }
}
