/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.registrosinformacionnueva;

import backend.principal.FuncionamientoAplicacion;
import backend.principal.Libro;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author michael
 */
public class ListadoLibros extends javax.swing.JPanel {

    private JTextField textFieldBusqueda;
    private TableRowSorter<TableModel> rowSorter;

    /**
     * Creates new form ListadoLibros
     */
    public ListadoLibros() {
        initComponents();
        this.actualizarTablaLibros();
        agregarCampoBusqueda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
 private void agregarCampoBusqueda() {
        textFieldBusqueda = new JTextField();
        textFieldBusqueda.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla(textFieldBusqueda.getText());
            }
        });
        add(textFieldBusqueda, java.awt.BorderLayout.NORTH);
    }

    private void filtrarTabla(String texto) {
        if (rowSorter == null) {
            rowSorter = new TableRowSorter<>(tablaLibros.getModel());
            tablaLibros.setRowSorter(rowSorter);
        }
        if (texto.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }

    public void actualizarTablaLibros() {
        String[] columnas = {"Código", "Título", "Autor", "Editorial", "Fecha de publicación", "NO. Copias"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, FuncionamientoAplicacion.listaLibros.size());
        tablaLibros.setModel(modelo);

        TableModel modeloDatos = tablaLibros.getModel();
        for (int i = 0; i < FuncionamientoAplicacion.listaLibros.size(); i++) {
            Libro libro = FuncionamientoAplicacion.listaLibros.get(i);
            modeloDatos.setValueAt(libro.getCodigo(), i, 0);
            modeloDatos.setValueAt(libro.getTitulo(), i, 1);
            modeloDatos.setValueAt(libro.getAutor(), i, 2);
            modeloDatos.setValueAt(libro.getEditorial(), i, 3);
            modeloDatos.setValueAt(libro.getFechaPublicacion(), i, 4);
            modeloDatos.setValueAt(libro.getCantidadCopias(), i, 5);
        }
        FuncionamientoAplicacion.guardarSerializableLibros();
    }
}
