package frontend.registrosinformacionnueva;

import backend.principal.Estudiante;
import backend.principal.FuncionamientoAplicacion;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ryoumen_kyoma
 */
public class ListadoPrestamos extends javax.swing.JPanel {

    private JTextField textFieldBusqueda;
    private DefaultTableModel modelo;

    /**
     * Creates new form ListadoEstudiantes
     */
    public ListadoPrestamos() {
        initComponents();
        actualizarTablaPrestamos();
        mostrarArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tablaPrestamos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPrestamos);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrestamos;
    // End of variables declaration//GEN-END:variables

    

    public void actualizarTablaPrestamos() {
        String[] columnas = {"Codigo del Libro", "Carnet", "Fecha"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, FuncionamientoAplicacion.listaEstudiantes.size());
        tablaPrestamos.setModel(modelo);

        TableModel modeloDatos = tablaPrestamos.getModel();
        for (int i = 0; i < FuncionamientoAplicacion.listaPrestamos.size(); i++) {
            Estudiante estudiante = FuncionamientoAplicacion.listaEstudiantes.get(i);
            modeloDatos.setValueAt(estudiante.getCarnet(), i, 0);
            modeloDatos.setValueAt(estudiante.getNombre(), i, 1);
            modeloDatos.setValueAt(estudiante.getCodigoCarrera(), i, 2);
            modeloDatos.setValueAt(estudiante.getFechaNacimiento(), i, 3);
        }
        FuncionamientoAplicacion.guardarSerializableLibros();
    }
    
    private void mostrarArray() {
        System.out.println("mostrando array");
        for (int i = 0; i < FuncionamientoAplicacion.listaEstudiantes.size(); i++) {
            System.out.println(FuncionamientoAplicacion.listaEstudiantes.get(i).toString());
            
        }
    }
}
